# Generated by Django 5.2.4 on 2026-04-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_herobanner_chips_herobanner_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='whatsapp_template',
            field=models.TextField(blank=True, default='Halo Tim *{divisi}*,\n\nSaya tertarik untuk mendapatkan informasi lebih lanjut terkait layanan yang tersedia.\n\nBerikut data saya:\nNama:\nJurusan/Fakultas/Universitas:\nLembaga/Instansi:\nKebutuhan (konsultasi/bootcamp/kelas private/dll):\n\nMohon informasinya. Terima kasih.', help_text='Gunakan {divisi} untuk nama divisi otomatis. Kosongkan untuk format default.', null=True),
        ),
    ]
