# Generated by Django 5.2.4 on 2026-04-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_companyconfig_whatsapp_template'),
        ('programs', '0004_alter_program_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsAnnouncement',
            fields=[
            ],
            options={
                'verbose_name': 'Pengumuman / Banner',
                'verbose_name_plural': 'Pengumuman / Banner',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('programs.announcement',),
        ),
        migrations.CreateModel(
            name='CmsBlogArticle',
            fields=[
            ],
            options={
                'verbose_name': 'Artikel Blog',
                'verbose_name_plural': 'Artikel Blog',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('programs.blogarticle',),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='footer_description',
            field=models.TextField(default='Aji Institute adalah lembaga pelatihan dan konsultasi riset, metodologi, dan manajemen terpadu yang membantu individu dan korporasi.', help_text='Teks singkat perkenalan di bagian footer web.'),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='social_linkedin',
            field=models.CharField(blank=True, help_text='Link akun LinkedIn (opsional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='social_tiktok',
            field=models.CharField(blank=True, help_text='Link akun TikTok (misal: https://tiktok.com/@ajiinstitute)', max_length=100, null=True),
        ),
    ]
