# Generated by Django 5.2.4 on 2026-04-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_cmsannouncement_cmsblogarticle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Popup')),
                ('subtitle', models.TextField(blank=True, help_text='Teks pendek di bawah judul (opsional).', null=True, verbose_name='Subjudul / Deskripsi')),
                ('image', models.ImageField(help_text='Upload gambar flyer (JPG/PNG). Rasio potret lebih baik.', upload_to='popup/', verbose_name='Gambar / Flyer')),
                ('badge', models.CharField(blank=True, help_text='Teks badge kecil di atas judul, misal: "Info Terbaru". Kosongkan jika tidak perlu.', max_length=60, null=True, verbose_name='Badge / Label')),
                ('badge_color', models.CharField(default='#F0A500', help_text='Kode warna hex, misal: #F0A500 (emas) atau #2563EB (biru).', max_length=7, verbose_name='Warna Badge')),
                ('highlights', models.TextField(blank=True, help_text='Satu poin per baris. Akan ditampilkan sebagai bullet list di popup.', null=True, verbose_name='Poin Highlight')),
                ('cta_text', models.CharField(default='Hubungi Kami via WhatsApp', max_length=100, verbose_name='Teks Tombol CTA')),
                ('cta_url', models.URLField(help_text='Link tujuan tombol, misal: link WhatsApp atau halaman program.', verbose_name='URL Tombol CTA')),
                ('show_on_main_site', models.BooleanField(default=True, help_text='Centang untuk menampilkan popup di aji-institute.com', verbose_name='Tampilkan di Aji Institute')),
                ('show_on_ajistat', models.BooleanField(default=True, help_text='Centang untuk menampilkan popup di ajistat.aji-institute.com', verbose_name='Tampilkan di AjiStat')),
                ('is_active', models.BooleanField(default=False, help_text='Hanya SATU popup yang boleh aktif sekaligus. Aktifkan ini untuk menampilkannya.', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Welcome Popup',
                'verbose_name_plural': 'Welcome Popup',
                'ordering': ['-updated_at'],
            },
        ),
    ]
