# Generated by Django 5.2.4 on 2026-04-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_popup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popup',
            options={'ordering': ['order', '-updated_at'], 'verbose_name': 'Welcome Popup', 'verbose_name_plural': 'Welcome Popup'},
        ),
        migrations.AddField(
            model_name='popup',
            name='order',
            field=models.IntegerField(default=0, help_text='Urutan tampil di slider (makin kecil makin awal).', verbose_name='Urutan Slider'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Aktifkan untuk menampilkan popup ini di slider.', verbose_name='Aktif'),
        ),
    ]
