# Generated by Django 5.2.13 on 2026-04-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_popup_multi_active_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='slide_duration',
            field=models.IntegerField(default=5, help_text='Berapa detik slide ini tampil sebelum otomatis pindah ke slide berikutnya. Default: 5 detik.', verbose_name='Durasi Slide (detik)'),
        ),
        migrations.AlterField(
            model_name='companyconfig',
            name='whatsapp',
            field=models.CharField(default='6282319341735', help_text='Format: 628xxx (tanpa + atau 0)', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyconfig',
            name='whatsapp_display',
            field=models.CharField(default='+62 823-1934-1735', max_length=50),
        ),
    ]
