# Generated by Django 5.2.4 on 2026-04-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Singkat')),
                ('message', models.TextField(help_text='Teks yang tampil di banner. Bisa menyertakan link.', verbose_name='Pesan')),
                ('type', models.CharField(choices=[('info', 'Info (Biru)'), ('promo', 'Promo (Hijau)'), ('warning', 'Penting (Kuning)')], default='info', max_length=20, verbose_name='Jenis / Warna')),
                ('cta_label', models.CharField(blank=True, help_text='Misal: Daftar Sekarang', max_length=80, verbose_name='Label Tombol (opsional)')),
                ('cta_url', models.URLField(blank=True, verbose_name='URL Tombol (opsional)')),
                ('is_active', models.BooleanField(default=True, help_text='Hanya pengumuman aktif yang tampil di website', verbose_name='Aktif?')),
                ('start_date', models.DateField(blank=True, help_text='Kosongkan = langsung aktif', null=True, verbose_name='Mulai Tampil')),
                ('end_date', models.DateField(blank=True, help_text='Kosongkan = tidak ada batas waktu', null=True, verbose_name='Berakhir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pengumuman / Banner',
                'verbose_name_plural': 'Pengumuman / Banner',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Judul Artikel')),
                ('slug', models.SlugField(help_text='Otomatis dari judul. Contoh: liputan-pikiran-rakyat-2025', max_length=300, unique=True)),
                ('excerpt', models.TextField(help_text='Deskripsi singkat artikel (1-2 kalimat)', verbose_name='Ringkasan')),
                ('category', models.CharField(choices=[('liputan-media', 'Liputan Media'), ('statistika', 'Statistika'), ('metodologi', 'Metodologi'), ('kualitatif', 'Kualitatif'), ('akademik', 'Akademik'), ('tools-software', 'Tools & Software')], max_length=50, verbose_name='Kategori')),
                ('tag', models.CharField(blank=True, help_text='Label tag kecil di kartu. Contoh: Jurnalistik', max_length=100)),
                ('date', models.DateField(verbose_name='Tanggal Artikel')),
                ('image_url', models.CharField(blank=True, help_text='Path lokal: /images/nama-file.jpg  atau URL eksternal', max_length=300, verbose_name='Path / URL Gambar')),
                ('color', models.CharField(default='#1B3A8C', help_text='Warna aksen kategori (hex). Contoh: #E11D48', max_length=7)),
                ('source_name', models.CharField(blank=True, help_text='Misal: Pikiran Rakyat, Kompas, atau kosongkan', max_length=100, verbose_name='Nama Sumber / Media')),
                ('is_external', models.BooleanField(default=False, help_text='Centang jika artikel ada di website lain', verbose_name='Link Eksternal?')),
                ('external_url', models.URLField(blank=True, help_text='Isi jika "Link Eksternal" dicentang', verbose_name='URL Artikel Eksternal')),
                ('is_published', models.BooleanField(default=True, verbose_name='Tampilkan di Website?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artikel Blog',
                'verbose_name_plural': 'Artikel Blog',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
