# Generated by Django 5.2.13 on 2026-04-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_announcement_blogarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='brand',
            field=models.CharField(choices=[('ajistat', 'AjiStat — Statistika & Riset'), ('ajibiz', 'AjiBiz — Bisnis & Kewirausahaan'), ('ajipr', 'AjiPR — Public Relations & Komunikasi'), ('ajidigi', 'AjiDigi — Digital Marketing'), ('ajilangua', 'AjiLangua — Bahasa & Komunikasi')], default='ajistat', help_text='Kategori brand program ini (AjiStat, AjiBiz, dll)', max_length=20, verbose_name='Brand / Sub-program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='demo_video_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
