# Generated by Django 6.0.5 on 2026-07-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_add_youtube_url_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='show_rundown',
            field=models.BooleanField(default=False, help_text='Aktifkan untuk menampilkan tabel rundown jadwal harian di halaman program', verbose_name='Tampilkan Rundown Harian?'),
        ),
    ]
