# Generated by Django 6.0.5 on 2026-07-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_add_show_rundown'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='registration_link',
            field=models.URLField(blank=True, help_text='Isi dengan link eksternal (misal Google Form). Jika kosong, otomatis diarahkan ke WhatsApp.', null=True, verbose_name='Link Pendaftaran (Opsional)'),
        ),
    ]
