# Generated by Django 6.0.5 on 2026-08-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_program_registration_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_video_hero',
            field=models.BooleanField(default=False, help_text='Centang untuk menampilkan video program ini sebagai video utama (autoplay) di halaman Video. Pastikan hanya 1 program yang dicentang.', verbose_name='⭐ Jadikan Hero di Halaman Video?'),
        ),
    ]
