"""
AjiStat — Seed Data Script
Run: python manage.py shell < apps/seed.py
"""
import os, sys, django

# Tambahkan direktori root backend ke sistem path agar modul 'config' terbaca
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE_DIR)

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from apps.programs.models import Program, Testimonial

# Clear existing
Program.objects.all().delete()
Testimonial.objects.all().delete()

programs = [
    # ─── BOOTCAMP ────────────────────────────────────────────
    {
        "title": "Bootcamp Analisis Data dengan SPSS: Dari Dasar hingga Mahir",
        "slug": "bootcamp-spss-dasar-mahir",
        "type": "bootcamp",
        "description": "Kuasai SPSS untuk kebutuhan riset akademik dan profesional. Dari instalasi, input data, statistik deskriptif, uji asumsi, hingga regresi dan interpretasi hasil yang siap masuk laporan.",
        "price": 350000,
        "original_price": 500000,
        "status": "upcoming",
        "tags": ["SPSS", "Statistik", "Riset", "Pemula"],
        "curriculum": [
            "Pengenalan SPSS dan antarmuka",
            "Input & cleaning data",
            "Statistik deskriptif & frekuensi",
            "Uji normalitas & homogenitas",
            "Uji beda: T-test, ANOVA",
            "Korelasi & regresi linier",
            "Interpretasi & pelaporan hasil",
        ],
        "facilitator_name": "Dr. Ahmad Fauzan, M.Stat",
        "facilitator_title": "Dosen Statistika, Peneliti Kuantitatif",
        "facilitator_bio": "10+ tahun pengalaman mengajar statistika. Penulis 30+ artikel terindeks Scopus.",
        "facilitator_avatar": "AF",
        "demo_video_url": "/videos/video-preview-pelatihan-spss.mp4",
        "thumbnail_color": "#162660",
        "duration": "4 Hari (8 Sesi Live Zoom)",
        "schedule": "10 April 2026",
        "is_featured": True,
    },
    {
        "title": "Bootcamp SmartPLS: Structural Equation Modeling untuk Riset",
        "slug": "bootcamp-smartpls-sem",
        "type": "bootcamp",
        "description": "Pelajari metode SEM-PLS untuk penelitian bisnis, manajemen, dan sosial. Dari desain model, outer loading, AVE, CR, hingga uji hipotesis bootstrapping.",
        "price": 400000,
        "original_price": 600000,
        "status": "upcoming",
        "tags": ["SmartPLS", "SEM", "Kuantitatif"],
        "curriculum": [
            "Pengenalan SEM dan SmartPLS",
            "Desain model reflektif & formatif",
            "Measurement model: outer loading, AVE, CR",
            "Structural model: path coefficient",
            "Bootstrapping & uji hipotesis",
            "Mediasi & moderasi",
            "Pelaporan hasil SEM",
        ],
        "facilitator_name": "Dr. Rizky Pratama, M.M",
        "facilitator_title": "Pakar SEM & Metodologi Penelitian",
        "facilitator_bio": "Konsultan riset untuk lebih dari 200 tesis dan disertasi S2/S3.",
        "facilitator_avatar": "RP",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#2568B5",
        "duration": "3 Hari (6 Sesi Live Zoom)",
        "schedule": "17 April 2026",
        "is_featured": True,
    },
    {
        "title": "Bootcamp R Studio: Analisis Statistika Lanjutan untuk Peneliti",
        "slug": "bootcamp-r-studio-lanjutan",
        "type": "bootcamp",
        "description": "Analisis data lanjutan dengan R: regresi lanjut, clustering, PCA, hingga visualisasi publikasi-grade dengan ggplot2.",
        "price": 450000,
        "original_price": 650000,
        "status": "upcoming",
        "tags": ["R", "Data Science", "Visualisasi"],
        "curriculum": [
            "Setup R & RStudio",
            "Manipulasi data dengan dplyr",
            "Visualisasi dengan ggplot2",
            "Regresi lanjut & GLM",
            "Analisis kluster",
            "PCA & dimensionality reduction",
            "Membuat laporan dengan R Markdown",
        ],
        "facilitator_name": "Siti Nuraini, M.Si",
        "facilitator_title": "Data Scientist & Peneliti Biostatistik",
        "facilitator_bio": "Praktisi data science dengan pengalaman riset di bidang kesehatan dan sosial.",
        "facilitator_avatar": "SN",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#1a4a8a",
        "duration": "5 Hari (10 Sesi Live Zoom)",
        "schedule": "24 April 2026",
        "is_featured": True,
    },
    {
        "title": "Bootcamp Python untuk Analisis Data dan Machine Learning Dasar",
        "slug": "bootcamp-python-data-ml",
        "type": "bootcamp",
        "description": "Mulai dari Python dasar hingga pandas, numpy, scikit-learn untuk analisis data dan model ML sederhana.",
        "price": 500000,
        "original_price": 750000,
        "status": "upcoming",
        "tags": ["Python", "Machine Learning", "Data Science"],
        "curriculum": [
            "Python dasar untuk data",
            "Pandas & numpy",
            "Eksplorasi data (EDA)",
            "Visualisasi dengan matplotlib & seaborn",
            "Preprocessing data",
            "Model regresi & klasifikasi",
            "Evaluasi model",
        ],
        "facilitator_name": "Bima Aditya, M.Kom",
        "facilitator_title": "ML Engineer & Data Science Educator",
        "facilitator_bio": "Pengalaman 7 tahun di industri teknologi, trainer bersertifikat Google.",
        "facilitator_avatar": "BA",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#0C1A45",
        "duration": "5 Hari (10 Sesi Live Zoom)",
        "schedule": "1 Mei 2026",
        "is_featured": False,
    },
    {
        "title": "Bootcamp Metodologi Penelitian Kuantitatif Komprehensif",
        "slug": "bootcamp-metodologi-kuantitatif",
        "type": "bootcamp",
        "description": "Dari latar belakang masalah, kerangka teori, instrumen, pengumpulan data, analisis hingga penarikan kesimpulan yang valid dan terstruktur.",
        "price": 350000,
        "original_price": 500000,
        "status": "recorded",
        "tags": ["Metodologi", "Kuantitatif", "Skripsi", "Tesis"],
        "curriculum": [
            "Filsafat penelitian kuantitatif",
            "Perumusan masalah & hipotesis",
            "Desain penelitian & sampling",
            "Instrumen & uji validitas-reliabilitas",
            "Teknik pengumpulan data",
            "Analisis & interpretasi",
            "Penulisan laporan penelitian",
        ],
        "facilitator_name": "Prof. Dr. Hendra Wijaya",
        "facilitator_title": "Guru Besar Metodologi Penelitian",
        "facilitator_bio": "Penulis buku metodologi penelitian yang digunakan di 50+ universitas Indonesia.",
        "facilitator_avatar": "HW",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#162660",
        "duration": "4 Hari Rekaman",
        "schedule": "Akses Seumur Hidup",
        "is_featured": False,
    },
    {
        "title": "Bootcamp Penulisan Artikel Ilmiah & Strategi Publikasi Scopus",
        "slug": "bootcamp-publikasi-scopus",
        "type": "bootcamp",
        "description": "Strategi menulis, mereview, dan mempublikasikan artikel ke jurnal terindeks Scopus dan Web of Science. Termasuk manuscript preparation dan response to reviewer.",
        "price": 450000,
        "original_price": 700000,
        "status": "upcoming",
        "tags": ["Scopus", "Publikasi", "Akademik"],
        "curriculum": [
            "Struktur artikel ilmiah internasional",
            "Pemilihan jurnal target",
            "Strategi penulisan abstract & keywords",
            "Literature review yang kuat",
            "Metodologi & hasil yang meyakinkan",
            "Response to reviewer",
            "Etika publikasi ilmiah",
        ],
        "facilitator_name": "Dr. Laila Maharani, M.Hum",
        "facilitator_title": "Editor Jurnal Internasional, H-index 12",
        "facilitator_bio": "Reviewer di 15+ jurnal terindeks Scopus. Membantu 100+ artikel berhasil dipublikasikan.",
        "facilitator_avatar": "LM",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#2568B5",
        "duration": "3 Hari (6 Sesi Live Zoom)",
        "schedule": "8 Mei 2026",
        "is_featured": False,
    },
    # ─── SHORT CLASS ──────────────────────────────────────────
    {
        "title": "Uji Validitas & Reliabilitas Instrumen dengan SPSS dalam 2 Jam",
        "slug": "short-validitas-reliabilitas-spss",
        "type": "short-class",
        "description": "Sesi singkat 2 jam: pelajari cara menguji validitas (pearson/corrected item-total) dan reliabilitas (cronbach alpha) instrumen penelitian dengan SPSS secara langsung.",
        "price": 99000,
        "original_price": 150000,
        "status": "upcoming",
        "tags": ["SPSS", "Validitas", "Pemula"],
        "curriculum": [
            "Konsep validitas & reliabilitas",
            "Input data kuesioner ke SPSS",
            "Uji validitas pearson",
            "Uji reliabilitas cronbach alpha",
            "Interpretasi & pelaporan",
        ],
        "facilitator_name": "Dr. Ahmad Fauzan, M.Stat",
        "facilitator_title": "Dosen Statistika",
        "facilitator_bio": "Spesialis instrumen penelitian dan analisis data.",
        "facilitator_avatar": "AF",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#4FA8D8",
        "duration": "2 Jam",
        "schedule": "5 April 2026",
        "is_featured": True,
    },
    {
        "title": "Visualisasi Data untuk Laporan Ilmiah dengan Python & Matplotlib",
        "slug": "short-visualisasi-python",
        "type": "short-class",
        "description": "Buat grafik dan chart publikasi-grade untuk skripsi, tesis, dan artikel ilmiah menggunakan Python, Matplotlib, dan Seaborn dalam 2 jam intensif.",
        "price": 120000,
        "original_price": 200000,
        "status": "upcoming",
        "tags": ["Python", "Visualisasi", "Intermediate"],
        "curriculum": [
            "Setup library matplotlib & seaborn",
            "Bar chart, line chart, scatter plot",
            "Boxplot & distribusi",
            "Kustomisasi warna & style akademik",
            "Export gambar resolusi tinggi",
        ],
        "facilitator_name": "Bima Aditya, M.Kom",
        "facilitator_title": "ML Engineer & Data Visualizer",
        "facilitator_bio": "Spesialis visualisasi data dan storytelling dengan Python.",
        "facilitator_avatar": "BA",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#4FA8D8",
        "duration": "2 Jam",
        "schedule": "12 April 2026",
        "is_featured": True,
    },
    {
        "title": "Cara Cepat Temukan Artikel Scopus Relevan dengan Teknik Boolean",
        "slug": "short-scopus-boolean-search",
        "type": "short-class",
        "description": "Kuasai teknik pencarian database Scopus, Web of Science, dan Google Scholar menggunakan boolean operator dan keyword strategy untuk literatur review yang komprehensif.",
        "price": 85000,
        "original_price": 130000,
        "status": "recorded",
        "tags": ["Scopus", "Literatur", "Akademik"],
        "curriculum": [
            "Boolean operator: AND, OR, NOT",
            "Pencarian di Scopus & WOS",
            "Filter berdasarkan subject area & kuartil",
            "Export referensi ke Mendeley/Zotero",
            "Tips literatur review sistematis",
        ],
        "facilitator_name": "Dr. Laila Maharani, M.Hum",
        "facilitator_title": "Editor Jurnal Internasional",
        "facilitator_bio": "Ahli strategi pencarian literatur ilmiah.",
        "facilitator_avatar": "LM",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#162660",
        "duration": "1.5 Jam Rekaman",
        "schedule": "Akses Seumur Hidup",
        "is_featured": False,
    },
    {
        "title": "Analisis Regresi Logistik dengan SPSS untuk Penelitian Kesehatan",
        "slug": "short-regresi-logistik-spss",
        "type": "short-class",
        "description": "Sesi khusus regresi logistik biner dan multinomial untuk penelitian klinis dan kesehatan masyarakat menggunakan SPSS. Termasuk interpretasi Odds Ratio.",
        "price": 149000,
        "original_price": 220000,
        "status": "upcoming",
        "tags": ["SPSS", "Kesehatan", "Regresi"],
        "curriculum": [
            "Konsep regresi logistik",
            "Asumsi & prasyarat",
            "Regresi logistik biner di SPSS",
            "Interpretasi odds ratio & CI",
            "Uji goodness of fit",
        ],
        "facilitator_name": "Dr. Ahmad Fauzan, M.Stat",
        "facilitator_title": "Biostatistician",
        "facilitator_bio": "Konsultan biostatistik untuk penelitian kesehatan masyarakat.",
        "facilitator_avatar": "AF",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#2568B5",
        "duration": "3 Jam",
        "schedule": "19 April 2026",
        "is_featured": False,
    },
    {
        "title": "Penulisan Bab IV & V Skripsi: Hasil, Pembahasan, dan Kesimpulan",
        "slug": "short-penulisan-bab-4-5",
        "type": "short-class",
        "description": "Panduan praktis menulis bab hasil dan pembahasan yang kuat dan tidak plagiat: cara menyajikan data, menganalisis, mendiskusikan, dan menarik kesimpulan yang tepat.",
        "price": 99000,
        "original_price": 150000,
        "status": "recorded",
        "tags": ["Skripsi", "Penulisan", "Akademik", "Pemula"],
        "curriculum": [
            "Struktur bab IV & V yang benar",
            "Cara menyajikan tabel & gambar",
            "Menulis pembahasan yang kuat",
            "Menghindari plagiarisme",
            "Kesimpulan & saran yang tepat",
        ],
        "facilitator_name": "Prof. Dr. Hendra Wijaya",
        "facilitator_title": "Guru Besar Metodologi",
        "facilitator_bio": "Pembimbing ratusan skripsi dan tesis S1/S2.",
        "facilitator_avatar": "HW",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#1a4a8a",
        "duration": "2 Jam Rekaman",
        "schedule": "Akses Seumur Hidup",
        "is_featured": True,
    },
    {
        "title": "NVivo untuk Analisis Data Kualitatif: Koding & Tema",
        "slug": "short-nvivo-kualitatif",
        "type": "short-class",
        "description": "NVivo untuk penelitian kualitatif: import data wawancara/FGD, koding tematik, membuat node, dan mengekspor hasil analisis yang siap dilaporkan.",
        "price": 175000,
        "original_price": 250000,
        "status": "upcoming",
        "tags": ["NVivo", "Kualitatif", "Intermediate"],
        "curriculum": [
            "Pengenalan NVivo & interface",
            "Import data teks & audio",
            "Koding manual & otomatis",
            "Membuat nodes & themes",
            "Visualisasi: word cloud & matrix",
            "Export hasil analisis",
        ],
        "facilitator_name": "Siti Nuraini, M.Si",
        "facilitator_title": "Peneliti Kualitatif Bersertifikat",
        "facilitator_bio": "Spesialis analisis data kualitatif dan mixed methods.",
        "facilitator_avatar": "SN",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#4FA8D8",
        "duration": "3 Jam",
        "schedule": "26 April 2026",
        "is_featured": False,
    },
    # ─── AJIBIZ ────────────────────────────────────────────
    {
        "title": "Bootcamp Business Plan & Analisis Kelayakan Usaha",
        "slug": "bootcamp-ajibiz-business-plan",
        "type": "bootcamp",
        "description": "Susun business plan yang komprehensif: dari Canvas model, analisis finansial, hingga strategi go-to-market yang menarik investor dan klien.",
        "price": 450000,
        "original_price": 700000,
        "status": "upcoming",
        "tags": ["AjiBiz", "Business Plan", "Manajemen", "Wirausaha"],
        "curriculum": [
            "Business Model Canvas dari nol",
            "Analisis pasar & kompetitor",
            "Proyeksi keuangan & break-even",
            "Strategi pemasaran & branding",
            "Presentasi investor pitch",
            "Studi kasus UMKM nyata",
        ],
        "facilitator_name": "Hendra Gunawan, M.M",
        "facilitator_title": "Business Consultant & Entrepreneur",
        "facilitator_bio": "10 tahun pengalaman mendampingi UMKM dan startup Indonesia.",
        "facilitator_avatar": "HG",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#1B3A8C",
        "duration": "3 Hari (6 Sesi Live Zoom)",
        "schedule": "15 April 2026",
        "is_featured": True,
    },
    {
        "title": "Short Class: Strategi Pemasaran & Personal Branding untuk UMKM",
        "slug": "short-ajibiz-pemasaran-branding",
        "type": "short-class",
        "description": "Kuasai teknik pemasaran modern, membangun brand yang kuat, dan meningkatkan penjualan bisnis Anda dalam 3 jam intensif.",
        "price": 129000,
        "original_price": 200000,
        "status": "upcoming",
        "tags": ["AjiBiz", "Marketing", "Strategi", "Branding", "UMKM"],
        "curriculum": [
            "Identitas brand & positioning",
            "Strategi konten media sosial bisnis",
            "Personal branding untuk pemilik bisnis",
            "Teknik closing & persuasi pelanggan",
            "Tools gratis untuk pemasaran digital",
        ],
        "facilitator_name": "Rina Kusumawardani, M.M",
        "facilitator_title": "Marketing Strategist",
        "facilitator_bio": "Praktisi pemasaran digital dengan 8 tahun pengalaman.",
        "facilitator_avatar": "RK",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#162058",
        "duration": "3 Jam Live Zoom",
        "schedule": "20 April 2026",
        "is_featured": True,
    },
    {
        "title": "Short Class: Leadership & Manajemen Tim yang Efektif",
        "slug": "short-ajibiz-leadership",
        "type": "short-class",
        "description": "Kembangkan jiwa kepemimpinan, pelajari cara memimpin tim lintas-generasi, dan bangun budaya kerja yang produktif.",
        "price": 149000,
        "original_price": 220000,
        "status": "upcoming",
        "tags": ["AjiBiz", "Leadership", "Manajemen", "Komunikasi Bisnis"],
        "curriculum": [
            "Gaya kepemimpinan yang efektif",
            "Delegasi tugas & manajemen prioritas",
            "Memimpin tim remote/hybrid",
            "Konflik di tempat kerja & resolusinya",
            "Membangun budaya kerja positif",
        ],
        "facilitator_name": "Rizky Pratama, M.M",
        "facilitator_title": "Leadership Coach",
        "facilitator_bio": "Coach kepemimpinan bersertifikat ICF dengan 200+ klien profesional.",
        "facilitator_avatar": "RP",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#1B3A8C",
        "duration": "2 Jam Live Zoom",
        "schedule": "22 April 2026",
        "is_featured": False,
    },
    # ─── AJIDIGI ──────────────────────────────────────────
    {
        "title": "Bootcamp Digital Marketing: Dari Strategi hingga Eksekusi",
        "slug": "bootcamp-ajidigi-digital-marketing",
        "type": "bootcamp",
        "description": "Kuasai seluruh ekosistem digital marketing: SEO, Google Ads, Meta Ads, content strategy, dan analytics untuk bisnis modern.",
        "price": 499000,
        "original_price": 750000,
        "status": "upcoming",
        "tags": ["AjiBiz", "AjiDigi", "Digital Marketing", "Ads", "SEO"],
        "curriculum": [
            "Strategi digital marketing end-to-end",
            "SEO on-page & off-page",
            "Google Ads & Search Campaign",
            "Meta Ads (Facebook & Instagram)",
            "Content planning & copywriting",
            "Google Analytics 4 & reporting",
            "A/B Testing & optimasi kampanye",
        ],
        "facilitator_name": "Siti Nuraini, M.Si",
        "facilitator_title": "Digital Marketing Specialist",
        "facilitator_bio": "7 tahun pengalaman mengelola kampanye digital untuk brand nasional.",
        "facilitator_avatar": "SN",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#162058",
        "duration": "4 Hari (8 Sesi Live Zoom)",
        "schedule": "5 Mei 2026",
        "is_featured": True,
    },
    {
        "title": "Short Class: Copywriting & Caption Kreatif untuk Social Media",
        "slug": "short-ajidigi-copywriting",
        "type": "short-class",
        "description": "Menulis copywriting yang menarik, caption Instagram/TikTok yang viral, dan teks iklan yang konversi tinggi dalam 2 jam.",
        "price": 99000,
        "original_price": 150000,
        "status": "recorded",
        "tags": ["AjiDigi", "Copywriting", "Content", "Social Media"],
        "curriculum": [
            "Formula copywriting AIDA & PAS",
            "Caption IG & TikTok yang engage",
            "Headline iklan yang klik",
            "Teknik storytelling brand",
            "Template caption siap pakai",
        ],
        "facilitator_name": "Bima Aditya, M.Kom",
        "facilitator_title": "Content Strategist",
        "facilitator_bio": "Penulis konten dengan 5 juta pembaca per bulan.",
        "facilitator_avatar": "BA",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#1B3A8C",
        "duration": "2 Jam Rekaman",
        "schedule": "Akses Seumur Hidup",
        "is_featured": True,
    },
    {
        "title": "Short Class: SEO Dasar untuk Website & Blog Bisnis",
        "slug": "short-ajidigi-seo",
        "type": "short-class",
        "description": "Optimasi website Anda agar tampil di halaman pertama Google: keyword research, on-page SEO, dan teknik link building dasar.",
        "price": 119000,
        "original_price": 180000,
        "status": "upcoming",
        "tags": ["AjiDigi", "SEO", "Digital Marketing", "Analytics"],
        "curriculum": [
            "Cara kerja algoritma Google",
            "Keyword research dengan tools gratis",
            "Optimasi on-page: title, meta, heading",
            "Konten SEO-friendly",
            "Link building dasar",
        ],
        "facilitator_name": "Siti Nuraini, M.Si",
        "facilitator_title": "SEO & Content Specialist",
        "facilitator_bio": "Spesialis SEO dengan portofolio 50+ website yang berhasil masuk halaman 1 Google.",
        "facilitator_avatar": "SN",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#162058",
        "duration": "2.5 Jam Live Zoom",
        "schedule": "28 April 2026",
        "is_featured": False,
    },
    # ─── AJIPR ────────────────────────────────────────────
    {
        "title": "Bootcamp Public Speaking & Presentasi Profesional",
        "slug": "bootcamp-ajipr-public-speaking",
        "type": "bootcamp",
        "description": "Kuasai seni berbicara di depan umum: dari teknik vokal, body language, manajemen nervus, hingga presentasi persuasif yang meninggalkan kesan.",
        "price": 420000,
        "original_price": 650000,
        "status": "upcoming",
        "tags": ["AjiPR", "Public Speaking", "Komunikasi", "Presentasi"],
        "curriculum": [
            "Psikologi rasa gugup & cara mengatasinya",
            "Teknik vokal: intonasi, diksi, tempo",
            "Body language & eye contact",
            "Struktur presentasi yang persuasif",
            "Storytelling untuk pidato & pitch",
            "Latihan praktik dengan feedback langsung",
            "Workshop MC & moderator",
        ],
        "facilitator_name": "Laila Maharani, M.Hum",
        "facilitator_title": "Public Speaking Trainer & MC Profesional",
        "facilitator_bio": "15 tahun pengalaman sebagai trainer komunikasi dan MC event nasional.",
        "facilitator_avatar": "LM",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#1B3A8C",
        "duration": "3 Hari (6 Sesi Live Zoom)",
        "schedule": "12 Mei 2026",
        "is_featured": True,
    },
    {
        "title": "Short Class: Personal Branding Digital untuk Karier & Bisnis",
        "slug": "short-ajipr-personal-branding",
        "type": "short-class",
        "description": "Bangun citra profesional Anda secara online: optimasi LinkedIn, konten personal brand, dan strategi tampil sebagai thought leader.",
        "price": 129000,
        "original_price": 200000,
        "status": "upcoming",
        "tags": ["AjiPR", "Personal Branding", "Komunikasi", "LinkedIn"],
        "curriculum": [
            "Apa itu personal brand & mengapa penting",
            "Optimasi profil LinkedIn",
            "Strategi konten untuk personal brand",
            "Cara dapat klien/peluang lewat media sosial",
            "Konsistensi brand dan nilai profesional",
        ],
        "facilitator_name": "Hendra Gunawan, M.M",
        "facilitator_title": "Personal Branding Coach",
        "facilitator_bio": "Membantu 300+ profesional membangun brand digital yang kuat.",
        "facilitator_avatar": "HG",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#162058",
        "duration": "2 Jam Live Zoom",
        "schedule": "3 Mei 2026",
        "is_featured": True,
    },
    {
        "title": "Short Class: Media Relation & Menulis Press Release Efektif",
        "slug": "short-ajipr-media-relation",
        "type": "short-class",
        "description": "Pelajari cara membangun relasi dengan jurnalis, menulis siaran pers yang dimuat media, dan mengelola krisis komunikasi.",
        "price": 149000,
        "original_price": 225000,
        "status": "upcoming",
        "tags": ["AjiPR", "Media Relation", "Storytelling", "Komunikasi"],
        "curriculum": [
            "Cara kerja media & jurnalis",
            "Struktur press release standar media",
            "Tips pitching berita ke jurnalis",
            "Manajemen krisis komunikasi dasar",
            "Studi kasus brand nasional",
        ],
        "facilitator_name": "Laila Maharani, M.Hum",
        "facilitator_title": "PR Strategist & Media Trainer",
        "facilitator_bio": "Mantan jurnalis nasional, kini konsultan PR untuk korporat dan pemerintahan.",
        "facilitator_avatar": "LM",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#1B3A8C",
        "duration": "2.5 Jam Live Zoom",
        "schedule": "10 Mei 2026",
        "is_featured": False,
    },
    # ─── AJILANGUA ────────────────────────────────────────
    {
        "title": "Bootcamp IELTS & TOEFL Preparation — Target Band 7+",
        "slug": "bootcamp-ajilangua-ielts-toefl",
        "type": "bootcamp",
        "description": "Persiapan intensif IELTS dan TOEFL: strategi menjawab soal, latihan tiap section, simulasi tes, dan tips target band 7+ atau skor 550+.",
        "price": 480000,
        "original_price": 750000,
        "status": "upcoming",
        "tags": ["AjiLangua", "IELTS", "TOEFL", "Beasiswa", "Bahasa Inggris"],
        "curriculum": [
            "Listening: strategi prediksi dan note-taking",
            "Reading: skimming & scanning cepat",
            "Writing Task 1 & 2 (IELTS) / Essay (TOEFL)",
            "Speaking: fluency, coherence, vocabulary",
            "Simulasi tes full-length",
            "Feedback personal dari tutor",
            "Tips manajemen waktu ujian",
        ],
        "facilitator_name": "Tim Fasilitator AjiLangua",
        "facilitator_title": "English & Academic Instructor",
        "facilitator_bio": "Tutor bersertifikat CELTA/Cambridge dengan pengalaman melatih ribuan peserta tes internasional.",
        "facilitator_avatar": "LG",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#162058",
        "duration": "5 Hari (10 Sesi Live Zoom)",
        "schedule": "19 Mei 2026",
        "is_featured": True,
    },
    {
        "title": "Short Class: Academic Writing & Research Paper dalam 3 Jam",
        "slug": "short-ajilangua-academic-writing",
        "type": "short-class",
        "description": "Tulis paper akademik berkualitas internasional: struktur yang benar, abstract yang kuat, dan gaya penulisan ilmiah yang memukau.",
        "price": 149000,
        "original_price": 220000,
        "status": "upcoming",
        "tags": ["AjiLangua", "Academic Writing", "Scopus", "Bahasa Inggris"],
        "curriculum": [
            "Struktur paper internasional (IMRaD)",
            "Menulis abstract yang efektif",
            "Paraphrase & citation yang benar",
            "Gaya bahasa ilmiah & hedging",
            "Koreksi grammar dalam konteks akademik",
        ],
        "facilitator_name": "Tim Fasilitator AjiLangua",
        "facilitator_title": "Academic Writing Coach",
        "facilitator_bio": "Spesialis penulisan akademik ilmiah dengan H-index 8.",
        "facilitator_avatar": "LG",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#1B3A8C",
        "duration": "3 Jam Live Zoom",
        "schedule": "17 Mei 2026",
        "is_featured": True,
    },
    {
        "title": "Private Class: English Speaking Practice & Business Communication",
        "slug": "private-ajilangua-speaking-business",
        "type": "private-class",
        "description": "Sesi privat 1-on-1 untuk meningkatkan kelancaran berbicara bahasa Inggris dalam konteks bisnis, presentasi, dan interview karier global.",
        "price": 299000,
        "original_price": None,
        "status": "open",
        "tags": ["AjiLangua", "Speaking", "Business English", "Bahasa Inggris"],
        "curriculum": [
            "Sesi speaking freestyle + koreksi langsung",
            "Simulasi meeting & negosiasi bisnis",
            "Latihan presentasi profesional",
            "Vocabulary building untuk dunia kerja",
            "Pronunciation & intonasi",
        ],
        "facilitator_name": "Tim Fasilitator AjiLangua",
        "facilitator_title": "English Communication Coach",
        "facilitator_bio": "Native-level fluency coach dengan background di perusahaan multinasional.",
        "facilitator_avatar": "LG",
        "demo_video_url": "https://www.youtube.com/embed/dQw4w9WgXcQ",
        "thumbnail_color": "#162058",
        "duration": "60 Menit / Sesi (Fleksibel)",
        "schedule": "Jadwal menyesuaikan peserta",
        "is_featured": False,
    },
]

for p in programs:
    Program.objects.create(**p)

print(f"✓ Created {len(programs)} programs")

testimonials = [
    {"name": "Rika Amalia", "role": "Mahasiswi S2 Manajemen, UGM", "program_name": "Bootcamp SmartPLS", "rating": 5,
     "comment": "SEM yang tadinya terasa sangat rumit jadi mudah dimengerti. Langsung bisa saya terapkan di tesis saya. Fasilitatornya sabar dan menjelaskan dengan sangat baik!"},
    {"name": "Dimas Santoso", "role": "Peneliti Muda, Lembaga Riset Independen", "program_name": "Konsultasi AJI Statistik", "rating": 5,
     "comment": "Konsultasi analisis data sangat profesional. Tim membantu dari pemilihan metode hingga interpretasi hasil. Artikel saya berhasil diterima jurnal Sinta 2!"},
    {"name": "Putri Handayani", "role": "Mahasiswi S1 Psikologi, UI", "program_name": "Short Class Validitas SPSS", "rating": 5,
     "comment": "2 jam yang sangat padat tapi mudah dipahami. Uji validitas instrumen skripsi saya jadi lebih percaya diri. Worth it banget!"},
    {"name": "Arif Budiman", "role": "Dosen Muda, Universitas Brawijaya", "program_name": "Bootcamp Publikasi Scopus", "rating": 5,
     "comment": "Strategi penulisan yang diajarkan sangat praktikal. Artikel pertama saya akhirnya diterima jurnal Q2 Scopus setelah mengikuti bootcamp ini."},
    {"name": "Maya Lestari", "role": "Mahasiswi Doktoral, IPB University", "program_name": "Bootcamp R Studio", "rating": 5,
     "comment": "Materinya komprehensif dan update. Visualisasi dengan ggplot2 yang saya pelajari langsung dipakai untuk disertasi saya. Highly recommended!"},
]

for t in testimonials:
    Testimonial.objects.create(**t)

print(f"✓ Created {len(testimonials)} testimonials")
print("✓ Seed data complete!")
