"""
AjiStat — Seed Data Script
Run: python manage.py shell < apps/seed.py
"""
import os, sys, django

# Tambahkan direktori root backend ke sistem path agar modul 'config' terbaca
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE_DIR)

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from apps.programs.models import Program, Testimonial

# Clear existing
Program.objects.all().delete()
Testimonial.objects.all().delete()

programs = [
    # ─── BOOTCAMP AJISTAT ────────────────────────────────────
    {
        "title": "Bootcamp Analisis Data dengan SPSS: Dari Dasar hingga Mahir",
        "slug": "bootcamp-spss-dasar-mahir",
        "type": "bootcamp",
        "description": "Kuasai SPSS untuk kebutuhan riset akademik dan profesional. Dari instalasi, input data, statistik deskriptif, uji asumsi, hingga regresi dan interpretasi hasil yang siap masuk laporan.",
        "price": 350000,
        "original_price": 500000,
        "status": "upcoming",
        "tags": ["SPSS", "Statistik", "Riset", "Pemula"],
        "curriculum": [
            "Pengenalan SPSS dan antarmuka",
            "Input & cleaning data",
            "Statistik deskriptif & frekuensi",
            "Uji normalitas & homogenitas",
            "Uji beda: T-test, ANOVA",
            "Korelasi & regresi linier",
            "Interpretasi & pelaporan hasil",
        ],
        "facilitator_name": "Aji Pamoso, S.Si, M.T",
        "facilitator_title": "Founder AjiStat | Peneliti & Konsultan Data",
        "facilitator_bio": "Pendiri Aji Institute dengan pengalaman mendampingi 5.000+ klien riset akademik dan profesional.",
        "facilitator_avatar": "AP",
        "demo_video_url": "/videos/video-preview-pelatihan-spss.mp4",
        "thumbnail_color": "#162660",
        "duration": "4 Hari (8 Sesi Live Zoom)",
        "schedule": "10 April 2026",
        "brand": "ajistat",
        "is_featured": True,
    },
    {
        "title": "Bootcamp SmartPLS: Structural Equation Modeling untuk Riset",
        "slug": "bootcamp-smartpls-sem",
        "type": "bootcamp",
        "description": "Pelajari metode SEM-PLS untuk penelitian bisnis, manajemen, dan sosial. Dari desain model, outer loading, AVE, CR, hingga uji hipotesis bootstrapping.",
        "price": 400000,
        "original_price": 600000,
        "status": "upcoming",
        "tags": ["SmartPLS", "SEM", "Kuantitatif"],
        "curriculum": [
            "Pengenalan SEM dan SmartPLS",
            "Desain model reflektif & formatif",
            "Measurement model: outer loading, AVE, CR",
            "Structural model: path coefficient",
            "Bootstrapping & uji hipotesis",
            "Mediasi & moderasi",
            "Pelaporan hasil SEM",
        ],
        "facilitator_name": "Aji Pamoso, S.Si, M.T",
        "facilitator_title": "Peneliti Kuantitatif & Pakar SEM",
        "facilitator_bio": "Konsultan riset SmartPLS dengan pengalaman mendampingi ratusan tesis dan disertasi S2/S3.",
        "facilitator_avatar": "AP",
        "demo_video_url": "",
        "thumbnail_color": "#2568B5",
        "duration": "3 Hari (6 Sesi Live Zoom)",
        "schedule": "17 April 2026",
        "brand": "ajistat",
        "is_featured": True,
    },
    {
        "title": "Bootcamp R Studio: Analisis Statistika Lanjutan untuk Peneliti",
        "slug": "bootcamp-r-studio-lanjutan",
        "type": "bootcamp",
        "description": "Analisis data lanjutan dengan R: regresi lanjut, clustering, PCA, hingga visualisasi publikasi-grade dengan ggplot2.",
        "price": 450000,
        "original_price": 650000,
        "status": "upcoming",
        "tags": ["R", "Data Science", "Visualisasi"],
        "curriculum": [
            "Setup R & RStudio",
            "Manipulasi data dengan dplyr",
            "Visualisasi dengan ggplot2",
            "Regresi lanjut & GLM",
            "Analisis kluster",
            "PCA & dimensionality reduction",
            "Membuat laporan dengan R Markdown",
        ],
        "facilitator_name": "Aji Pamoso, S.Si, M.T",
        "facilitator_title": "Data Scientist & Peneliti Statistika",
        "facilitator_bio": "Praktisi analisis data dengan spesialisasi R dan biostatistik terapan.",
        "facilitator_avatar": "AP",
        "demo_video_url": "",
        "thumbnail_color": "#1a4a8a",
        "duration": "5 Hari (10 Sesi Live Zoom)",
        "schedule": "24 April 2026",
        "brand": "ajistat",
        "is_featured": True,
    },
    {
        "title": "Bootcamp Metodologi Penelitian Kuantitatif Komprehensif",
        "slug": "bootcamp-metodologi-kuantitatif",
        "type": "bootcamp",
        "description": "Dari latar belakang masalah, kerangka teori, instrumen, pengumpulan data, analisis hingga penarikan kesimpulan yang valid dan terstruktur.",
        "price": 350000,
        "original_price": 500000,
        "status": "recorded",
        "tags": ["Metodologi", "Kuantitatif", "Skripsi", "Tesis"],
        "curriculum": [
            "Filsafat penelitian kuantitatif",
            "Perumusan masalah & hipotesis",
            "Desain penelitian & sampling",
            "Instrumen & uji validitas-reliabilitas",
            "Teknik pengumpulan data",
            "Analisis & interpretasi",
            "Penulisan laporan penelitian",
        ],
        "facilitator_name": "Aji Pamoso, S.Si, M.T",
        "facilitator_title": "Konsultan Metodologi Penelitian",
        "facilitator_bio": "Berpengalaman membimbing ratusan mahasiswa dari berbagai universitas dalam penyusunan metodologi riset.",
        "facilitator_avatar": "AP",
        "demo_video_url": "",
        "thumbnail_color": "#162660",
        "duration": "4 Hari Rekaman",
        "schedule": "Akses Seumur Hidup",
        "brand": "ajistat",
        "is_featured": False,
    },
    {
        "title": "Bootcamp Penulisan Artikel Ilmiah & Strategi Publikasi Scopus",
        "slug": "bootcamp-publikasi-scopus",
        "type": "bootcamp",
        "description": "Strategi menulis, mereview, dan mempublikasikan artikel ke jurnal terindeks Scopus dan Web of Science. Termasuk manuscript preparation dan response to reviewer.",
        "price": 450000,
        "original_price": 700000,
        "status": "upcoming",
        "tags": ["Scopus", "Publikasi", "Akademik"],
        "curriculum": [
            "Struktur artikel ilmiah internasional",
            "Pemilihan jurnal target",
            "Strategi penulisan abstract & keywords",
            "Literature review yang kuat",
            "Metodologi & hasil yang meyakinkan",
            "Response to reviewer",
            "Etika publikasi ilmiah",
        ],
        "facilitator_name": "Aji Pamoso, S.Si, M.T",
        "facilitator_title": "Peneliti & Konsultan Publikasi Ilmiah",
        "facilitator_bio": "Berpengalaman mendampingi dosen dan mahasiswa dalam proses publikasi artikel ilmiah terindeks.",
        "facilitator_avatar": "AP",
        "demo_video_url": "",
        "thumbnail_color": "#2568B5",
        "duration": "3 Hari (6 Sesi Live Zoom)",
        "schedule": "8 Mei 2026",
        "brand": "ajistat",
        "is_featured": False,
    },
    {
        "title": "Bootcamp Public Relation: Strategi Komunikasi Profesional",
        "slug": "bootcamp-public-relation",
        "type": "bootcamp",
        "description": "Pelajari strategi public relations dan komunikasi profesional. Dari membangun citra positif, media relation, hingga manajemen krisis untuk perusahaan dan institusi.",
        "price": 1500000,
        "original_price": 2500000,
        "status": "upcoming",
        "tags": ["AjiPR", "Public Relation", "Komunikasi"],
        "curriculum": [
            "Pengantar Public Relation",
            "Strategi Komunikasi Profesional",
            "Media Relation & Press Release",
            "Manajemen Krisis",
            "Personal & Corporate Branding",
            "Praktek Simulasi Press Conference",
        ],
        "facilitator_name": "Aji Pamoso, S.Si, M.T",
        "facilitator_title": "Konsultan PR & Komunikasi",
        "facilitator_bio": "Berpengalaman dalam bidang komunikasi strategis dan public relation.",
        "facilitator_avatar": "AP",
        "demo_video_url": "/videos/bootcamp_public-relation.mp4",
        "thumbnail_color": "#1E3A6E",
        "duration": "4 Hari (8 Sesi Live Zoom)",
        "schedule": "Akan Datang",
        "brand": "ajipr",
        "is_featured": True,
    },
    # ─── SHORT CLASS AJISTAT ─────────────────────────────────
    {
        "title": "Uji Validitas & Reliabilitas Instrumen dengan SPSS dalam 2 Jam",
        "slug": "short-validitas-reliabilitas-spss",
        "type": "short-class",
        "description": "Sesi singkat 2 jam: pelajari cara menguji validitas (pearson/corrected item-total) dan reliabilitas (cronbach alpha) instrumen penelitian dengan SPSS secara langsung.",
        "price": 99000,
        "original_price": 150000,
        "status": "upcoming",
        "tags": ["SPSS", "Validitas", "Pemula"],
        "curriculum": [
            "Konsep validitas & reliabilitas",
            "Input data kuesioner ke SPSS",
            "Uji validitas pearson",
            "Uji reliabilitas cronbach alpha",
            "Interpretasi & pelaporan",
        ],
        "facilitator_name": "Aji Pamoso, S.Si, M.T",
        "facilitator_title": "Konsultan Statistika & Instrumen Penelitian",
        "facilitator_bio": "Spesialis instrumen penelitian dan analisis data kuantitatif.",
        "facilitator_avatar": "AP",
        "demo_video_url": "",
        "thumbnail_color": "#4FA8D8",
        "duration": "2 Jam",
        "schedule": "5 April 2026",
        "brand": "ajistat",
        "is_featured": True,
    },
    {
        "title": "Analisis Regresi Logistik dengan SPSS untuk Penelitian Kesehatan",
        "slug": "short-regresi-logistik-spss",
        "type": "short-class",
        "description": "Sesi khusus regresi logistik biner dan multinomial untuk penelitian klinis dan kesehatan masyarakat menggunakan SPSS. Termasuk interpretasi Odds Ratio.",
        "price": 149000,
        "original_price": 220000,
        "status": "upcoming",
        "tags": ["SPSS", "Kesehatan", "Regresi"],
        "curriculum": [
            "Konsep regresi logistik",
            "Asumsi & prasyarat",
            "Regresi logistik biner di SPSS",
            "Interpretasi odds ratio & CI",
            "Uji goodness of fit",
        ],
        "facilitator_name": "Aji Pamoso, S.Si, M.T",
        "facilitator_title": "Konsultan Biostatistik & Kesehatan",
        "facilitator_bio": "Berpengalaman dalam riset kuantitatif bidang kesehatan masyarakat dan epidemiologi.",
        "facilitator_avatar": "AP",
        "demo_video_url": "",
        "thumbnail_color": "#2568B5",
        "duration": "3 Jam",
        "schedule": "19 April 2026",
        "brand": "ajistat",
        "is_featured": False,
    },
    {
        "title": "Penulisan Bab IV & V Skripsi: Hasil, Pembahasan, dan Kesimpulan",
        "slug": "short-penulisan-bab-4-5",
        "type": "short-class",
        "description": "Panduan praktis menulis bab hasil dan pembahasan yang kuat dan tidak plagiat: cara menyajikan data, menganalisis, mendiskusikan, dan menarik kesimpulan yang tepat.",
        "price": 99000,
        "original_price": 150000,
        "status": "recorded",
        "tags": ["Skripsi", "Penulisan", "Akademik", "Pemula"],
        "curriculum": [
            "Struktur bab IV & V yang benar",
            "Cara menyajikan tabel & gambar",
            "Menulis pembahasan yang kuat",
            "Menghindari plagiarisme",
            "Kesimpulan & saran yang tepat",
        ],
        "facilitator_name": "Aji Pamoso, S.Si, M.T",
        "facilitator_title": "Konsultan Penulisan Akademik",
        "facilitator_bio": "Pembimbing ratusan mahasiswa dalam penyelesaian skripsi dan tesis.",
        "facilitator_avatar": "AP",
        "demo_video_url": "",
        "thumbnail_color": "#1a4a8a",
        "duration": "2 Jam Rekaman",
        "schedule": "Akses Seumur Hidup",
        "brand": "ajistat",
        "is_featured": True,
    },
    {
        "title": "Bootcamp NVivo untuk Analisis Data Kualitatif: Koding & Tema",
        "slug": "bootcamp-nvivo-kualitatif",
        "type": "bootcamp",
        "description": "NVivo untuk penelitian kualitatif: import data wawancara/FGD, koding tematik, membuat node, dan mengekspor hasil analisis yang siap dilaporkan.",
        "price": 350000,
        "original_price": 500000,
        "status": "upcoming",
        "tags": ["AjiStat", "NVivo", "Kualitatif", "Intermediate"],
        "curriculum": [
            "Pengenalan NVivo & interface",
            "Import data teks & audio",
            "Koding manual & otomatis",
            "Membuat nodes & themes",
            "Visualisasi: word cloud & matrix",
            "Export hasil analisis",
        ],
        "facilitator_name": "Aji Pamoso, S.Si, M.T",
        "facilitator_title": "Peneliti Kualitatif & Mixed Methods",
        "facilitator_bio": "Berpengalaman dalam analisis data kualitatif dan NVivo untuk berbagai bidang riset.",
        "facilitator_avatar": "AP",
        "demo_video_url": "/videos/bootcamp_nvivo.mp4",
        "thumbnail_color": "#4FA8D8",
        "duration": "4 Hari (8 Sesi Live Zoom)",
        "schedule": "Akan Datang",
        "brand": "ajistat",
        "is_featured": True,
    },
    {
        "title": "Cara Cepat Temukan Artikel Scopus Relevan dengan Teknik Boolean",
        "slug": "short-scopus-boolean-search",
        "type": "short-class",
        "description": "Kuasai teknik pencarian database Scopus, Web of Science, dan Google Scholar menggunakan boolean operator dan keyword strategy untuk literatur review yang komprehensif.",
        "price": 85000,
        "original_price": 130000,
        "status": "recorded",
        "tags": ["Scopus", "Literatur", "Akademik"],
        "curriculum": [
            "Boolean operator: AND, OR, NOT",
            "Pencarian di Scopus & WOS",
            "Filter berdasarkan subject area & kuartil",
            "Export referensi ke Mendeley/Zotero",
            "Tips literatur review sistematis",
        ],
        "facilitator_name": "Aji Pamoso, S.Si, M.T",
        "facilitator_title": "Peneliti & Konsultan Literatur Ilmiah",
        "facilitator_bio": "Berpengalaman dalam strategi literatur review sistematis dan pencarian sumber ilmiah.",
        "facilitator_avatar": "AP",
        "demo_video_url": "",
        "thumbnail_color": "#162660",
        "duration": "1.5 Jam Rekaman",
        "schedule": "Akses Seumur Hidup",
        "brand": "ajistat",
        "is_featured": False,
    },
    # ─── PRIVATE CLASS AJISTAT ───────────────────────────────
    {
        "title": "Private Class: Analisis Data Skripsi/Tesis 1-on-1",
        "slug": "private-ajistat-analisis-data",
        "type": "private-class",
        "description": "Sesi privat langsung bersama konsultan AjiStat untuk membantu pengolahan dan analisis data penelitian Anda. Materi disesuaikan 100% dengan kebutuhan riset.",
        "price": 200000,
        "original_price": None,
        "status": "upcoming",
        "tags": ["SPSS", "SmartPLS", "Skripsi", "Tesis", "Privat"],
        "curriculum": [
            "Konsultasi metode & alat analisis",
            "Pendampingan pengolahan data langsung",
            "Interpretasi hasil analisis bersama",
            "Review & perbaikan output",
            "Sesi tanya jawab fleksibel",
        ],
        "facilitator_name": "Aji Pamoso, S.Si, M.T",
        "facilitator_title": "Konsultan Data Privat",
        "facilitator_bio": "Tersedia untuk sesi privat 1-on-1 dengan jadwal fleksibel malam dan weekend.",
        "facilitator_avatar": "AP",
        "demo_video_url": "",
        "thumbnail_color": "#162660",
        "duration": "60-90 Menit / Sesi",
        "schedule": "Jadwal menyesuaikan peserta",
        "brand": "ajistat",
        "is_featured": True,
    },
    {
        "title": "Private Class: Konsultasi Metodologi Penelitian & Skripsi",
        "slug": "private-ajistat-metodologi",
        "type": "private-class",
        "description": "Bimbingan metodologi penelitian dari perumusan masalah, pemilihan metode, hingga penyusunan bab III yang kuat. Sangat cocok untuk mahasiswa yang stuck di metodologi.",
        "price": 175000,
        "original_price": None,
        "status": "open",
        "tags": ["Metodologi", "Skripsi", "Tesis", "Privat"],
        "curriculum": [
            "Diskusi masalah & tujuan penelitian",
            "Pemilihan desain & metode yang tepat",
            "Panduan penyusunan bab III",
            "Review kerangka pikir & hipotesis",
            "Saran perbaikan section krusial",
        ],
        "facilitator_name": "Aji Pamoso, S.Si, M.T",
        "facilitator_title": "Konsultan Metodologi Riset",
        "facilitator_bio": "Berpengalaman membimbing ratusan mahasiswa dalam menyempurnakan metodologi penelitian mereka.",
        "facilitator_avatar": "AP",
        "demo_video_url": "",
        "thumbnail_color": "#2568B5",
        "duration": "60 Menit / Sesi",
        "schedule": "Jadwal menyesuaikan peserta",
        "brand": "ajistat",
        "is_featured": False,
    },
]

for p in programs:
    Program.objects.create(**p)

print(f"✓ Created {len(programs)} programs")

testimonials = [
    {"name": "Rika Amalia", "role": "Mahasiswi S2 Manajemen, UGM", "program_name": "Bootcamp SmartPLS", "rating": 5,
     "comment": "SEM yang tadinya terasa sangat rumit jadi mudah dimengerti. Langsung bisa saya terapkan di tesis saya. Pak Aji sabar dan menjelaskan dengan sangat baik!"},
    {"name": "Dimas Santoso", "role": "Peneliti Muda, Lembaga Riset Independen", "program_name": "Konsultasi AjiStat", "rating": 5,
     "comment": "Konsultasi analisis data sangat profesional. Tim membantu dari pemilihan metode hingga interpretasi hasil. Artikel saya berhasil diterima jurnal Sinta 2!"},
    {"name": "Putri Handayani", "role": "Mahasiswi S1 Psikologi, UI", "program_name": "Short Class Validitas SPSS", "rating": 5,
     "comment": "2 jam yang sangat padat tapi mudah dipahami. Uji validitas instrumen skripsi saya jadi lebih percaya diri. Worth it banget!"},
    {"name": "Arif Budiman", "role": "Dosen Muda, Universitas Brawijaya", "program_name": "Bootcamp Publikasi Scopus", "rating": 5,
     "comment": "Strategi penulisan yang diajarkan sangat praktikal. Artikel pertama saya akhirnya diterima jurnal Q2 Scopus setelah mengikuti bootcamp ini."},
    {"name": "Maya Lestari", "role": "Mahasiswi Doktoral, IPB University", "program_name": "Bootcamp R Studio", "rating": 5,
     "comment": "Materinya komprehensif dan update. Visualisasi dengan ggplot2 yang saya pelajari langsung dipakai untuk disertasi saya. Highly recommended!"},
]

for t in testimonials:
    Testimonial.objects.create(**t)

print(f"✓ Created {len(testimonials)} testimonials")
print("✓ Seed data complete!")
